- name: Prepare app directory
  hosts: appservers
  become: yes

  tasks:
    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Delete old config file
      file:
        path: /opt/app/config.yml
        state: absent

    - name: Create log file
      file:
        path: /opt/app/app.log
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: '0640'
