- name: Variables example
  hosts: web
  become: yes

  vars:
    package: nginx
    service: nginx

  tasks:
    - name: Install package
      apt:
        name: "{{ package }}"
        state: present

    - name: Start service
      service:
        name: "{{ service }}"
        state: started
