- name: Add cron job on remote server
  hosts: web
  become: yes

  tasks:
    - name: Run backup script daily at 5 AM
      cron:
        name: "Daily backup"
        minute: "0"
        hour: "5"
        job: "/usr/local/bin/backup.sh"
