- name: Add cron for ubuntu user
  hosts: web
  become: yes

  tasks:
    - name: ubuntu user's cron job
      cron:
        name: "check-disk"
        minute: "*/10"
        job: "/usr/local/bin/check_disk.sh"
        user: ubuntu
